tarantool/queue

- README.md
- init.lua
```
queue.take(0, 'q')     -- waits indefinitely
queue.take(0, 'q', -1) -- waits indefinitely
queue.take(0, 'q', 0)  -- returns immediately
queue.take(0, 'q', 1)  -- waits 1 second and returns
```
> Allow to return immediatly from queue.take() if there are no ready tasks

- README.md
As I can see, acknowledged task is marked with '-' and delayed is marked with '~'
> Acknowledged is marked with '-'

- CMakeLists.txt
Due to cmake syntax we have to set ENVIROMENT in a single
set_test_properties definition
> Fixed Cmake - set proper LUA path

- .travis.yml
Also I switched CI to 1.9 (set `PACKAGECLOUD_REPO` to `1_9`), because `1_7` bucket does not nave tarantool-dev package for Ubuntu Bionic.
Fixes #82.
> Add Ubuntu Bionic CI target: test and deploy

- queue/abstract/driver/fifottl.lua
- t/020-fifottl.t
fifottl_fiber pcalls fifottl_fiber_iteration and then handles
result. Returned error code comparison with box.error.READONLY
was not done properly. Now it is fixed.
Closes #96
> fix fifottl_fiber_iteration error handling

- queue/abstract.lua
- t/110-disconnect-trigger-check.t
> Fix task release in session disconnect

- .travis.yml
It reached EOL and the CI job fails with the following output:
```
sudo apt-get update > /dev/null
E: The repository 'http://security.ubuntu.com/ubuntu cosmic-security Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-updates Release' does not have a Release file.
E: The repository 'http://archive.ubuntu.com/ubuntu cosmic-backports Release' does not have a Release file.
```
> travis-ci: remove Ubuntu Cosmic

- README.md
- queue/abstract.lua
- queue/abstract/driver/fifo.lua
- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- t/000-init.t
- t/001-tube-init.t
- t/010-fifo.t
- t/020-fifottl.t
- t/030-utube.t
- t/040-utubettl.t
- t/050-ttl.t
- t/060-async.t
- t/070-compat.t
- t/080-otc-cb.t
- t/090-grant-check.t
- t/100-limfifottl.t
If some tasks have been taken and don't released before shutdown
of the tarantool instance (for example: tarantool instance has been killed)
such task go to 'hung' state (noone can take the task now).
So, we must release all taken tasks on start of the queue module.
Fixes #66
> Release all taken tasks on start

- queue/abstract.lua
- t/120-take-task-after-reconnect.t
We need to check of a session state before take a task after wait()
because session maybe in disconnecting state and task will be
hang in a take state after the session will be disconnected
Fixes #104
> Add a check of the session state before take a task

- .travis.yml
> travis-ci: fix publishing packages from tagged commits

- queue/abstract.lua
- t/130-release-all-tasks-on-start.t
* Added return in case of tarantool version < 1.7.5
* Instead of nil, an empty table is used as "opts" argument of the driver "release" method. This is the policy of the module "queue": "Check opts in abstract.lua, instead to check inside the driver".
* Added a test for release all tasks on start.
Follow-up #66
Fixes #121
ChangeLog: fix the tasks releases on start for some drivers(utubettl, fifottl, limfifottl).
> Fix release all tasks

- README.md
- queue/abstract.lua
Continue of https://github.com/tarantool/queue/pull/70
All the queue drivers do "transform(2, 1, state.DONE)" before returning the task from their "delete" method. Also, changing the status of a task from abstract.lua is a violation of encapsulation.
Patch changes:
* remove the unnecessary "transform" operation from "tube.delete"
* update description of a driver delete method in documentation
ChangeLog: Updated the requirements for  the "delete" driver method. Now, the method should change the state of a task to "done". Before, it was duplicated by external code.
> Remove unneeded transform in tube.delete

- queue/abstract.lua
In addition to the core queue drivers, customer drivers are exists. In the commit a check for a driver API implementation was added. Now, the consumer will be informed about the missing methods in the driver implementation.
Closes #126
ChangeLog: added notification about missing methods in the driver implementation.
ReleaseNotes: the "tasks_by_state" method was added to the driver API. See example implementation in one of the core drivers.
> Add driver API check

- .travis.yml
Ubuntu Disco is EOL and fails in CI on apt repositories updating with 'does not have a Release file' errors.
> travis-ci: remove Ubuntu Disco, add Focal

- queue/init.lua
- t/000-init.t
- t/150-lazy-start.t
Previously, if an instance was started in read_only mode,
it could throw an error when initializing the queue module,
like this: "Can't modify data because this instance is in
read-only mode".
To avoid such behavior the "lazy start" technique has been added:
The queue module is loaded immediately if the instance was
configured with read_only = false. Otherwise, a start is delayed
until the instance will be configured with read_only = false.
Closes #122
ChangeLog: add the ability to start an instance with a loaded queue module in read-only mode. In this case, a start of the module will be delayed until the instance will be configured with read_only = false.
> Add the "lazy start" technique to initialization stage

- queue/abstract/driver/fifo.lua
- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- t/160-validate-space.t
* For all queue drivers, the "new" method now checks for the presence of indexes created by the "create_space" method.
* If a space is creating with the "if_not_exist = true" option and a space with such name already exists (and this is not a tube of the required type), a conflict will be detected and an error will be thrown. This is necessary because we don't want to create additional indexes for the existing space and repurpose it into the "tube".
Closes #62
@ChangeLog Added space schema validation to all core drivers when creating a tube object. If a space is creating with the "if_not_exist = true" option and a space with such name already exists (and this is not a tube of the required type), a conflict will be detected and an error will be thrown.
> Add validation ot the space indexes

- queue/abstract.lua
- queue/init.lua
- t/170-register-driver-after-reload.t
Previously, if a custom driver is registered after calling box.cfg() it causes a problem when the instance will be restarted. The cause of the problem is an attempt to recreate a tube of custom type (which is not registered yet).
This bug is now fixed.
Fixes #137
@ChangeLog:  fix custom driver registration after reboot. Previously, if a custom driver is registered after calling box.cfg() it causes a problem when the instance will be restarted. The cause of the problem is an attempt to recreate a tube of custom type (which is not registered yet).
> fix custom driver registration after reboot

- queue/abstract.lua
The local variable "space" is defined twice in `recreate_tube()`.
First time it's a name of the space, the second - it's a space object.
If there is no space, we will try to thrown an error with the name of
the space, but `nil` will be used instead.
> fix the shadowing of the variable "space"

- .travis.yml
Ubuntu Eoan is EOL and fails in CI on apt repositories updating with
'does not have a Release file' errors.
> travis-ci: remove Ubuntu Eoan

- queue-scm-1.rockspec
GitHub is going to disable unencrypted Git protocol, so `git://` URLs
will stop working soon (see [1]).
[1]: https://github.blog/2021-09-01-improving-git-protocol-security-github/
Part of https://github.com/tarantool/tarantool/issues/6587
> rockspec: use git+https:// for git repository URL

- README.md
Fix typo in the content ("Session identification" -> "Session identify")
> Fix typo in the content

- .github/workflows/packaging.yml
This workflow is intended to run on a tag push to the 'master' branch
for creating and deploying module packages to S3 based repositories.
Closes #138
> cd: add package deploy workflow

- t/110-disconnect-trigger-check.t
- t/120-take-task-after-reconnect.t
- t/130-release-all-tasks-on-start.t
- t/140-register-driver-after-cfg.t
- t/150-lazy-start.t
- t/160-validate-space.t
- t/170-register-driver-after-reload.t
- t/180-work-with-uuid.t
Tests from 000 to 100 has vim modeline with filetype specified.
This patch adds filetype into remaining tests.
> tests: add missing vim modeline

- queue/abstract/driver/fifottl.lua
- t/190-work-with-ttl-buried-task.t
Now the task will be removed from the queue if a TTR has been installed for it. Fix allows you to delete a task only if it has a TTL
> fix fifottl bury

- README.md
- queue-scm-1.rockspec
- queue/CMakeLists.txt
- queue/abstract.lua
- queue/abstract/driver/fifo.lua
- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- queue/abstract/queue_session.lua
- queue/abstract/queue_state.lua
- queue/init.lua
- t/020-fifottl.t
- t/040-utubettl.t
- t/200-master-replica.t
- t/tnt/init.lua
This patch adds ability to use queue in a master-replica scheme.
The queue will monitor the operation mode of the tarantool and
perform the necessary actions accordingly.
This patch adds five states for queue: INIT, STARTUP, RUNNING, ENDING
and WAITING. When the tarantool is launched for the first time,
the state of the queue is always INIT until box.info.ro is false.
States switching scheme:
```mermaid
stateDiagram-v2
direction LR
w: Waiting
note right of w
monitor rw status
end note
s: Startup
note left of s
wait for maximum
upstream lag * 2
release all tasks
start driver
end note
Init --> s
r: Running
note right of r
queue is ready
end note
e: Ending
note left of e
stop driver
end note
w --> s: ro -> rw
s --> r
r --> e: rw -> ro
e --> w
```
In the STARTUP state, the queue is waiting …
> Add master-replica switching support

- README.md
The patch fixes markdown of `Table of contents` title.
Before and after the fix:
> readme: fix `Table of contents` title

- .github/workflows/publish.yml
> cd: add rockspec publishing

- .github/workflows/publish.yml
- README.md
- queue/abstract.lua
- queue/abstract/queue_session.lua
- t/190-work-with-ttl-buried-task.t
- t/200-master-replica.t
- t/210-cfg-in-replicaset.t
Execution of non-yielding DDL statements in transactions has been allowed only since Tarantool 2.2.1 [1]. We should avoid using DDL statements in transactions for older versions.
1. https://github.com/tarantool/tarantool/commit/f266559b167b4643c377724eebde9651877d6cc9
Closes #185 
This patchset includes a few fixes, mostly typos. So I recommend to review commits one by one. I can extract it into a separate pull request, if you wish, but the fixes are really small.
> abstract: fix switch in_replicaset value

- .github/workflows/packaging.yml
Due to a bug [1], packaging for Centos 7 does not work on ubuntu-latest. We need to downgrade a GitHub Actions runner image version until the problem is fixed.
1. https://github.com/packpack/packpack/issues/145
> cd: downgrade a runner image to ubuntu-18.04

- queue/abstract/queue_state.lua
Due to the fact that queue_state_fiber called box.ctrl.wait_r* every millisecond, the idle queue consumed more than 10% of CPU.
The proposed solution makes calls to box.ctrl.wait_r* blocking until the read/write mode is changed.
`Thus, CPU consumption is reduced to about ~1%.`
Below is a performance comparison using a script `t/benchmark/multi_consumer_work.lua` whith params consumers-count = 650 and batch-size = 5000 on CPU AMD Ryzen 5 5600U.
For comparison, consider three commits.
The first column is commit (9ff105b) before implementing queue_state_fiber.
The second column is commit (159a43d) before implementation of the described proposal. That is, queue_state_fiber calls box.ctrl.wait_r* every millisecond. 
The third column (offered) is the current offer, the box.ctrl.wait_r* blocking …
> abstract: reduced increased CPU consumption

- .github/workflows/packaging.yml
Fix the problem with sudoers for CentOS7.
For more details see:
https://github.com/packpack/packpack/issues/145
> Fix packaging for CentOS7

- .github/workflows/packaging.yml
According to [1] printing secrets to the log is not a best practice.
[1] https://docs.github.com/en/actions/security-guides/encrypted-secrets#accessing-your-secrets
> Remove printing secrets to the log

- .github/workflows/publish.yml
The problem is that on Ubuntu 22.04 luarocks v3 from the `tarantool-common` package is installed, but tarantoolctl from tarantool 1.10 uses luarocks v2.
See [1] for more details.
[1] https://github.com/tarantool/tarantool/issues/5429#issuecomment-1336162554
> cd: fix rockspec publishing

- queue/abstract.lua
- t/200-master-replica.t
- t/tnt/init.lua
In replicaset mode, tubes can be created and deleted on different nodes. Accordingly, it is necessary to rebuild the queue.tube index.
Close #202
> replicaset_mode: fix queue.tube indexes

- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utubettl.lua
After 1000 processed tuples an iteration fiber yields after each processed tuple. The problem was fixed by resetting a counter of processed tuples without yield.
Closes #208
> driver: fix yield in fifottl/utubettl

- queue/abstract/driver/fifo.lua
- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- t/220-mvcc.t
Taking the maximum of the index is an implicit transactions, so it is
always done with 'read-confirmed' mvcc isolation level.
It can lead to errors when trying to make parallel 'put' calls with mvcc enabled.
It is hapenning because 'max' for several puts in parallel will be the same since
read confirmed isolation level makes visible all transactions that finished the commit.
To fix it we wrap it with box.begin/commit and set right isolation level.
Current fix does not resolve that bug in situations when we already are in transaction
since it will open nested transactions.
Further work will be in another PR.
Part of #207
> driver: fix duplicate id error with mvvc on

- .github/workflows/fast_testing.yml
- t/tnt/init.lua
Deprecated `replication_connect_quorum` option was removed from replicaset setup method.
> ci: remove deprecated option from utils

- CHANGELOG.md
- queue/abstract.lua
- queue/init.lua
- t/200-master-replica.t
In replicaset mode, the user can attempt to call public methods on the replica start.
For example, a single script is used for master and replica.
This patch allows you to call a public method in the INIT state without
interrupting the script by exiting with an obscure error.
It will only log an attempt to call a method from the check_state function,
which is present at the beginning of each public method.
Closes #216
> replicaset_mode: allow api call in init state

- t/110-disconnect-trigger-check.t
We are going to make Tarantool shutdown graceful. Particularly for iproto graceful shutdown we wait while all connections are finished. On connection disconnect session disconnect triggers are invoked. If trigger hangs then graceful shutdown will hang too. And `os.exit()` do hang, it sleeps forever.
So `110-disconnect-trigger-check.t` test now hangs with iproto graceful shutdown patch.
Making `os.exit()` from disconnect trigger does not seem as a product case. So let's just change the test not to use `os.exit()`.
Required for full-ci pass of https://github.com/tarantool/tarantool/pull/9457
> test: dont os.exit() in session disconnect trigger

- queue/abstract/driver/utubettl.lua
- queue/abstract/queue_state.lua
We are going to finish all client (non-system) fibers in the process of Tarantool shutdown. First we cancel them and then wait for their finishing. So if the client fibers are not finished Tarantool shutdown is never finished too.
Currently some of queue fibers can not be finished and we got hang on integration testing of PR [1]. Let's fix it.
[1] PR with client fibers finishing on shutdown.
https://github.com/tarantool/tarantool/pull/9604
> abstract: make fibers cancellable

- CHANGELOG.md
- queue/init.lua
- t/230-orphan-not-stalling-init.t
Sometimes, instance could enter the queue initialization while still not running (for example, left in the orphan mode). This resulted in "lazy start". But Tarantool does not call `box.cfg {}` after leaving orphan mode, so queue could stuck in the `INIT` state.
Now if the instance is read-only,  separate fiber is watching for updates of its mode.
Note that this fix works only for Tarantool versions >= 2.10.0. This is because of used watchers.
Closes #226
> api: fix `INIT` state stuck

- CHANGELOG.md
- README.md
- queue/abstract.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- t/030-utube.t
- t/040-utubettl.t
- t/050-ttl.t
- t/160-validate-space.t
- t/benchmark/busy_utubes.lua
- t/benchmark/many_utubes.lua
If some of the utubes for tasks at the start of the queue were busy most of the time, `take` would slow down for every other task. This problem is fixed by creating a new space `space_ready`. It contains first task with `READY` status from each utube.
This solution shows great results for the stated problem, but with the cost of slowing the `put` method. Thus, this workaround is disabled by default. To enable it, user should set the `storage_mode = "ready_buffer"` as an option while creating the tube (or `queue.driver.utube.STORAGE_MODE_READY_BUFFER` for `utube` and `queue.driver.utubettl.STORAGE_MODE_READY_BUFFER` for `utubettl`). As example:
```lua
local test_queue = queue.create_tube('test_queue', 'utube',
{temporary = true, storage_mode = queue.driver.utube.STORAGE_MODE_READY_BUFFER}) …
```
> tube: fix slow take on busy utubes

- CHANGELOG.md
- queue/version.lua
The release introduces an experimental `storage_mode` option for the `utube` and `utubettl` drivers with the `memtx` engine. It could be used to create a `utube` or `utubettl` queue with an additional buffer space that stores only ready to take tasks.
```Lua
local tube = queue.create_tube('utube_with_ready_buffer', 'utube',
{storage_mode = queue.driver.utube.STORAGE_MODE_READY_BUFFER})
```
```Lua
local tube = queue.create_tube('utubettl_with_ready_buffer', 'utubettl',
{storage_mode = queue.driver.utubettl.STORAGE_MODE_READY_BUFFER})
```
The storage mode slower in general cases, but a much faster in cases when you have utubes with many tasks (see README.md for the performance comparison). So you should make your choice carefully.
* Experimental `storage_mode` option for creating a `utube` …
> Release 1.4.0

- CHANGELOG.md
- queue/version.lua
The release fixes too long release time by a `ttr` value or a `delay` timeout.
- Too long timings in the `utubettl` driver (#223).
> Release 1.4.1

- .github/workflows/fast_testing.yml
- CHANGELOG.md
- queue/abstract.lua
- queue/abstract/driver/fifo.lua
- queue/abstract/driver/fifottl.lua
- queue/abstract/driver/utube.lua
- queue/abstract/driver/utubettl.lua
- t/090-grant-check.t
There was a bug that grant for a user didn't work for spaces with `_ready_buffer` suffix.
After the patch the `grant` method was added for each driver that accounts the `grant` for all spaces.
Closes #237
> drivers: add grant method for all driver spaces

- CHANGELOG.md
- queue/abstract/queue_state.lua
The iterator does not handle the case where there are no records in the box.info.replication table in case of deleting old records, for examle:
```
- 1:
id: 1
uuid: 77f30d9a-d344-4f7a-a18c-578fb5ec2540
lsn: 4
name: null
3:
id: 3
uuid: 0ce528ca-ea35-42be-96b5-35ba610f9a3e
lsn: 0
downstream:
status: follow
idle: 0.14953243732452
vclock: {1: 4}
lag: 0.0015106201171875
name: null
```
It leads to the error and unable to start queue:
```
queue_state.lua:50: attempt to index a nil value
```
> core: failed to start if box.info.replication with gaps

- .github/workflows/packaging.yml
- .github/workflows/publish.yml
- .github/workflows/reusable_testing.yml
Bump actions to use ubuntu-24.04 for fixing the following GitHub warning:
The Ubuntu 20.04 Actions runner image will begin deprecation
on 2025-02-01.
Part of #TNTP-1918
> ci: bump actions to use ubuntu-24.04

- .github/workflows/fast_testing.yml
- CHANGELOG.md
- queue/abstract/driver/utubettl.lua
- t/040-utubettl.t
Previously, the function incorrectly retrieved the lowest priority task instead of the actual task in the ready buffer. This caused a logical error when the current task had the lowest priority.
The implementation error caused:
1. Incorrect selection of the lowest priority task for a take.
2. ready buffer appearing empty when tasks were actually in ready state.
> drivers: unable to take a task with utubettl

- CHANGELOG.md
The patch release fixes incorrect behavior of the utubettl driver with enabled `STORAGE_MODE_READY_BUFFER` mode.
- Incorrect choice by priority of task with utubettl driver + ready buffer mode (#244).
- Unable to take task with utubettl driver + ready buffer mode (#244).
> Release 1.4.4
